### ISSUE TITLE
Preview not displaying

### ISSUE THREAD

**Issue by MedicoreV8** [Cr4O13/easy-gauges#7]
The manual doesn't mention anything about it but the sample instruments all have a preview.png in the resources folder.
I've added my own preview.png, 360x360 pixels. run the logic.lua again, restarted air manager but it just doesn't show up when I place the instrument. It says "No image found".

**Comment by MedicoreV8** [comment]
I read up on instrument making on the official Air Manager Wiki and it mentions putting the preview.png in the root folder of the instrument. Maybe a good idea to update sample instruments because those all have the preview.png in the resources folder.

**Comment by Cr4O13** [comment]
The sample instruments assets here on GitHub have no folder structure. The preview images are there to show the instrument on the GitHub site. If you download, you need to place the assets where they belong yourself.
